### ISSUE TITLE
DataReader Refactoring TODO list

### ISSUE THREAD

**Issue by shijieliu** [NVIDIA/HugeCTR#69]
Description:
- [ ] Python friendly APIs: how to make the code and more uniform?
```
DataReader::set_source(){
   worker_group_.reset(new xxx_data_reader_worker_group);
}
# and no need to explicit call of start()
```
- [ ] Completely eliminate `repeat` from DataReader when it is ready, e.g., enable `set_source` for `Raw`
- [ ] Remove all the default arguments from DataReader
- [ ] Decouple Dataset source type from DataReader type (#169 #138)
- [ ] Make the number of DataReaders configurable (and perhaps automatic configuration for a given system)
- [ ] Support Eval for one epoch instead of specifying `n_batches`. It may require the change to Metrics as well. (@minseokl will see how TF and Pytorch tackle this issue)
- [ ] Remove the duplicate code if possible
Comments:
